AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy a lambda function that maintains the records status model state

Parameters:
  CodeBucketName:
    Type: String
    Description: Bucket containing lambda code zip file
  ZipFileName:
    Type: String
    Default: statusapi.zip


Resources:



  SMSSubFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Role: !GetAtt SMSSubExecutionRole.Arn
      CodeUri:
        Bucket: !Ref CodeBucketName
        Key: !Ref ZipFileName
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          SUBSCRIPTION_TABLE: foobar
      Events:
        GetInstances:
          Type: Api
          Properties:
            Path: /instances
            Method: get
        GetInstance:
          Type: Api
          Properties:
            Path: /instances/{id}
            Method: get




  SMSSubExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: metrics
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            Resource: '*'
      - PolicyName: xray
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - xray:PutTelemetryMetrics
            - xray:PutTraceSegments
            Resource: '*'
#      - PolicyName: ddb
#        PolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#          - Effect: Allow
#            Action:
#            - dynamodb:GetItem
#            - dynamodb:BatchGetItem
#            - dynamodb:PutItem
#            Resource: !GetAtt SMSSubTable.Arn
